spring:
  application:
    name: tdoer-swagger

server:
  port: 7110


## eureka client
eureka:
  instance:
    appname: ${spring.application.name}
    prefer-ip-address: true
    instance-enabled-onit: true
    ## endpoints
    home-page-url-path: /
    health-check-url-path: /management/health
    status-page-url-path: /management/info
    ## renew lease
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30

  client:
    ## basic
    enabled: true
    allow-redirects: false
    service-url:
      defaultZone: http://localhost:7020/eureka/

    ## register the instance
    register-with-eureka: true

    ## replicate instance info Eureka server
    initial-instance-info-replication-interval-seconds: 40
    instance-info-replication-interval-seconds: 30
    heartbeat-executor-exponential-back-off-bound: 10
    heartbeat-executor-thread-pool-size: 2
    on-demand-update-status-change: true

    ## fetch
    fetch-registry: true
    prefer-same-zone-eureka: true
    filter-only-up-instances: true
    g-zip-content: true
    disable-delta: false
    registry-fetch-interval-seconds: 30
    use-dns-for-fetching-service-urls: false
    cache-refresh-executor-thread-pool-size: 2
    cache-refresh-executor-exponential-back-off-bound: 10


    ## connections and timeouts
    eureka-server-total-connections: 200
    eureka-server-total-connections-per-host: 50
    eureka-connection-idle-timeout-seconds: 30
    eureka-server-connect-timeout-seconds: 5
    eureka-server-read-timeout-seconds: 8

    ## log
    log-delta-diff: false
## feign client
feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
zuul:
  ignored-services: "*"
  routes:
    coredata:
      path: /tdoer-core-coredata/**
      serviceId: tdoer-core-coredata
      stripPrefix: true
  retryable: true
swagger:
  server:
    names: tdoer-core-coredata